#pragma once

#define WIN32_LEAN_AND_MEAN

#include <Windows.h>
#include <stdio.h>
#include <cstdint>
#include <cstdlib>
#include <ctime>
#include <algorithm>
#include <iostream>
#include <vector>
#include <deque>
#include <random>
#include <Psapi.h>
#include <atomic>
#include <chrono>
#include <thread>
#include <assert.h>
#include <string>
#include <jni.h>
#include <gl\GL.h>
#include <gl\GLU.h>
#include <map>
#include <vector>
#include <functional>
#include <math.h>
#include <mutex>
#include <TlHelp32.h>
#include <array>
#include <fstream>
#include <tchar.h>
#include <iostream>
#include <stdio.h>
#include <tchar.h>
#include <thread>
#include <chrono>
#include <string>
#include <sstream>
#include <algorithm>
#include <Windows.h>
#include <fstream>
#include <TlHelp32.h>
#include <vector>
#include <winsock2.h>

#include "math/math.h"
#include "minhook/MinHook.h"